apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-varsler-mikrofrontend
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-varsler-secrets
  image: {{image}}
  port: 7500
  liveness:
    path: /tms-varsler-mikrofrontend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-varsler-mikrofrontend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-varsler-mikrofrontend/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://www.intern.dev.nav.no/tms-varsler-mikrofrontend"
    - "https://www.ansatt.dev.nav.no/tms-varsler-mikrofrontend"

  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
